kubeContext: homelab-master1

repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: grafana-community
    url: https://grafana-community.github.io/helm-charts
  - name: authelia
    url: https://charts.authelia.com

releases:
  - name: authelia
    namespace: authelia
    createNamespace: true
    chart: authelia/authelia
    version: 0.11.5
    values:
      - values/authelia.yaml
  - name: metrics-server
    namespace: kube-system
    createNamespace: false
    version: 3.13.0
    chart: metrics-server/metrics-server
  - name: traefik
    namespace: kube-system
    createNamespace: false
    chart: traefik/traefik
    version: 40.2.0
    values:
      - values/traefik.yaml
  - name: middleware
    namespace: default
    chart: ./charts/middleware
    secrets:
      - ./charts/middleware/secrets.enc.yaml
  - name: cnpg
    namespace: cnpg
    createNamespace: true
    chart: cnpg/cloudnative-pg
  - name: grafana-operator
    namespace: grafana-operator
    createNamespace: true
    chart: oci://ghcr.io/grafana/helm-charts/grafana-operator
    version: 5.23.0
    values:
      - values/grafana-operator.yaml
