apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: authelia
stringData:
  users_database.yml: |
    users:
      jcoelho93:
        disabled: false
        displayname: José Coelho
        password: "$argon2id$v=19$m=65536,t=3,p=4$2bmtaKAactHD6d4TunIkIA$FMfUWlXNaa1QPx3ohqUFbT94GNVJleSkVxYiKnoDLRs"
        email: "camilocoelho93@gmail.com"
        groups:
          - admins
