apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudbeaver-provided-connections
  namespace: cloudbeaver
data:
  provided_connections: |
    {
      "folders": {},
      "connections": {
        "prospero": {
          "provider": "postgresql",
          "driver": "postgres-jdbc",
          "name": "Prospero",
          "configuration": {
            "host": "prospero-db-rw.default.svc.cluster.local",
            "port": "5432",
            "database": "prospero",
            "configurationType": "MANUAL",
            "type": "production",
            "closeIdleConnection": true,
            "auth-model": "native",
            "bootstrap": {
              "autocommit": true
            }
          }
        }
      }
    }
