apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: default
  labels:
    dashboards: grafana
spec:
  config:
    server:
      domain: grafana.jlab.dedyn.io
    auth.ldap:
      enabled: "false"
  ingress:
    metadata:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    spec:
      rules:
        - host: grafana.jlab.dedyn.io
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
      tls:
        - hosts:
            - grafana.jlab.dedyn.io
